sonar.projectKey=Igor2427_Programa-o-web-1
sonar.organization=igor2427

sonar.sources=site-de-filmes/lib
sonar.tests=site-de-filmes/tests

sonar.javascript.lcov.reportPaths=site-de-filmes/coverage/lcov.info